services:

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    restart: always
    env_file:
      - ./.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - ${MINIO_HOST_VOLUME:-./volumes/minio/data}:/minio_data
    command: minio server /minio_data --console-address ":9001"
    ports:
      - "${EXPOSE_MINIO_SERVER_PORT:-9000}:9000"
      - "${EXPOSE_MINIO_CONSOLE_PORT:-9001}:9001"
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live' ]
      interval: 30s
      timeout: 20s
      retries: 3

  extract:
    image: weizhanjun/mineru-api:1.3.12
    restart: always
    env_file:
      - ./.env
    environment:
      ENABLE_S3_STORAGE: ${ENABLE_S3_STORAGE:-true}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-extractor}
      S3_BUCKET_PREFIX: ${S3_BUCKET_PREFIX:-deepservice}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:-http://minio:9000}
    ports:
      - "8000:8000"
    depends_on:
      - minio
