FROM nvidia/cuda:12.1.0-base-ubuntu22.04

COPY docker/sources.list /etc/apt/sources.list
# Set environment variables to non-interactive to avoid prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install necessary packages
RUN apt-get update && \
    apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa || true
RUN apt-get update ; apt-get install -y \
        python3.10 \
        python3.10-venv \
        python3.10-distutils \
        python3-pip \
        wget \
        git \
        libgl1 \
        libreoffice \
        fonts-noto-cjk \
        fonts-wqy-zenhei \
        fonts-wqy-microhei \
        ttf-mscorefonts-installer \
        fontconfig \
        libglib2.0-0 \
        libxrender1 \
        libsm6 \
        libxext6 \
        poppler-utils \
        && rm -rf /var/lib/apt/lists/*

# Set Python 3.10 as the default python3
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

#RUN pip3 install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple && \
RUN  pip3 install --no-cache-dir -U "magic-pdf[full]" -i https://mirrors.aliyun.com/pypi/simple

WORKDIR /mineru-api
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple

COPY models models
COPY docker/magic-pdf-cuda.json .

ENV MINERU_TOOLS_CONFIG_JSON=/mineru-api/magic-pdf-cuda.json
ENV PYTHONPATH=.
COPY app app


CMD ["python3", "app/main.py"]